//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;

import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class GJDepth3<R,A> extends GJDepth2<R,A> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //

   
	String printValue = "";
   
   public GJDepth3(Object labels) {
		super(labels);
	}

public R visit(NodeList n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeListOptional n, A argu) {
      if ( n.present() ) {
         R _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n, A argu) {
      if ( n.present() )
         return n.node.accept(this,argu);
      else
         return null;
   }

   public R visit(NodeSequence n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeToken n, A argu) { return null; }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> "MAIN"
    * f1 -> StmtList()
    * f2 -> "END"
    * f3 -> ( Procedure() )*
    * f4 -> <EOF>
    */
   public R visit(Goal n, A argu) {
      R _ret=null;
      ArgsPassed2 required = (ArgsPassed2) argu;
      stmtCount = 0;
      this.allocateForMethod = required.allocateForMethod;
	  this.spillForMethod = required.spillForMethod;
	  this.savedRegistersForMethod = required.savedRegistersForMethod;
	  this.argumentCount = required.argumentCount;
	  this.thirdArgumentForMethods = required.thirdArgumentForMethods;
	  this.stackSlots = required.stackSlots;
      n.f0.accept(this, argu);
      currentMethod = "main";
      int firstArgu = argumentCount.get(currentMethod);
      int secondArgu = stackSlots.get(currentMethod);
      int thirdArgu = thirdArgumentForMethods.get(currentMethod);
      printValue += "MAIN" + "[" + firstArgu + "][" + secondArgu + "][" + thirdArgu + "]\n";
      registerAllocated = allocateForMethod.get(currentMethod);
      spilledArg = spillForMethod.get(currentMethod);
      savedRegisters = savedRegistersForMethod.get(currentMethod);
      astore(savedRegisters, firstArgu);
      stmtCount++;
      n.f1.accept(this, argu);
      aload(savedRegisters, firstArgu);
      printValue += " END\n";
      n.f2.accept(this, argu);
      stmtCount++;
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      print(printValue);
      return _ret;
   }

   public void astore(Hashtable<Integer, String> savedRegisters, int argCount) {
	   printIntString(savedRegisters);
	   int size = savedRegisters.size();
	   print(size);
	   int i = 0;
	   int ct = 0;
	   if(argCount > 4) {
		   ct = argCount - 3;
	   }
	   while(i < size) {
		   printValue += "ASTORE SPILLED ARG " + ct++ + " s" + i + "\n";
		   i++;
	   }
   }

   public void aload(Hashtable<Integer, String> savedRegisters, int argCount) {
		   int size = savedRegisters.size();
		   int i = 0;
		   int ct = 0;
		   if(argCount > 4) {
			   ct = argCount - 3;
		   }
		   while(i < size) {
			   printValue += "ALOAD " + "s" + i + " SPILLED ARG " + ct++ + "\n";
			   i++;
		   }
	}
/**
    * f0 -> ( ( Label() )? Stmt() )*
    */
   public R visit(StmtList n, A argu) {
      R _ret=null;
      Vector<Node> n1 = n.f0.nodes;
      int i = 0;
      while(i < n1.size()) {
        stmtCount++;
        NodeSequence n2 = (NodeSequence) n1.elementAt(i);
        NodeOptional n3 = (NodeOptional) n2.elementAt(0);
        String label = (String) n3.accept(this, argu);

        if(n3.present()) {
            printValue += label + " : " + "\n";
        }
        n2.accept(this, argu);
        i++;
     }
      
      return _ret;
   }

   /**
    * f0 -> Label()
    * f1 -> "["
    * f2 -> IntegerLiteral()
    * f3 -> "]"
    * f4 -> StmtExp()
    */
   public R visit(Procedure n, A argu) {
      R _ret=null;
      currentMethod = (String) n.f0.accept(this, argu);
      stmtCount++;
      n.f1.accept(this, argu);
      int firstArgu = argumentCount.get(currentMethod);
      int secondArgu = stackSlots.get(currentMethod);
      int thirdArgu = thirdArgumentForMethods.get(currentMethod);
      registerAllocated = allocateForMethod.get(currentMethod);
      spilledArg = spillForMethod.get(currentMethod);
      savedRegisters = savedRegistersForMethod.get(currentMethod);
      printValue += currentMethod + "[" + firstArgu + "][" + secondArgu + "][" + thirdArgu + "]\n"; 
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      astore(savedRegisters, firstArgu);
      n.f4.accept(this, argu);
      aload(savedRegisters, firstArgu);
      printValue += "END\n";
      return _ret;
   }

   /**
    * f0 -> NoOpStmt()
    *       | ErrorStmt()
    *       | CJumpStmt()
    *       | JumpStmt()
    *       | HStoreStmt()
    *       | HLoadStmt()
    *       | MoveStmt()
    *       | PrintStmt()
    */
   public R visit(Stmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "NOOP"
    */
   public R visit(NoOpStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      printValue += " NOOP\n";
      return _ret;
   }

   /**
    * f0 -> "ERROR"
    */
   public R visit(ErrorStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      printValue += " ERROR\n";
      return _ret;
   }
   
   public String getOneTempForUse(int temp, boolean fl) {
	   if(registerAllocated.containsKey(temp)) {
		   return registerAllocated.get(temp);
	   }
	   else if(savedRegisters.containsKey(temp)) {
		   return savedRegisters.get(temp);
	   }
	   else {
		   if(fl) {
			   printValue += " ALOAD v1 SPILLED ARG " + spilledArg.get(temp) + "\n";
			   return "v1";
		   }
		   else {
			   printValue += " ALOAD v0 SPILLED ARG " + spilledArg.get(temp) + "\n";
			   return "v0";
		   }
			   
	   }
		   
   }
   /**
    * f0 -> "CJUMP"
    * f1 -> Temp()
    * f2 -> Label()
    */
   public R visit(CJumpStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      int temp = (Integer) n.f1.accept(this, argu);
      String reg = getOneTempForUse(temp, true);
      String label = (String) n.f2.accept(this, argu);
      printValue += " CJUMP " + reg + " " + label + " " +  "\n";
      return _ret;
   }

   /**
    * f0 -> "JUMP"
    * f1 -> Label()
    */
   public R visit(JumpStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      printValue += "JUMP " + (String) n.f1.accept(this, argu) + "\n";
      return _ret;
   }

   /**
    * f0 -> "HSTORE"
    * f1 -> Temp()
    * f2 -> IntegerLiteral()
    * f3 -> Temp()
    */
   public R visit(HStoreStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      int temp1 = (Integer) n.f1.accept(this, argu);
      int offset = (Integer) n.f2.accept(this, argu);
      int temp2 = (Integer) n.f3.accept(this, argu);
      String reg1 = getOneTempForUse(temp1, true);
      String reg2;
      if(reg1 == "v1") {
    	  reg2 = getOneTempForUse(temp2, false);
      }
      else {
    	  reg2 = getOneTempForUse(temp2, true);
      }
      printValue += " HSTORE " + reg1 + " " + offset + " " + reg2 + "\n";
//      if(reg1 == "v1") {
//    	  printValue += " ASTORE SPILLED ARG " + spilledArg.get(temp1) + " " + reg1 + "\n";
//      }
//      if(reg2 == "v1" || reg2 == " v0") {
//    	  printValue += " ASTORE SPILLED ARG " + spilledArg.get(temp2) + " " + reg2 + "\n";
//      }
      return _ret;
   }

   /**
    * f0 -> "HLOAD"
    * f1 -> Temp()
    * f2 -> Temp()
    * f3 -> IntegerLiteral()
    */
   public R visit(HLoadStmt n, A argu) {
	   R _ret=null;
	   n.f0.accept(this, argu);
	   int temp1 = (Integer) n.f1.accept(this, argu);
	   int temp2 = (Integer) n.f2.accept(this, argu);
	   int offset = (Integer) n.f3.accept(this, argu);
	   String reg1 = getOneTempForUse(temp1, true);
	   String reg2;
	   if(reg1 == "v1") {
		   reg2 = getOneTempForUse(temp2, false);
	   }		
	   else {
		   reg2 = getOneTempForUse(temp2, true);
	   }
	   
	   
	   
	   if(reg1 == "v1") {
	       printValue += " ASTORE SPILLED ARG " + spilledArg.get(temp1) + " " + reg1 + "\n";
	   }
	   else {
		   printValue += " HLOAD " + reg1 + " " + reg2 + " " + offset + "\n";
	   }
//	   if(reg2 == "v1" || reg2 == " v0") {
//	       printValue += " ASTORE SPILLED ARG " + spilledArg.get(temp2) + " " + reg2 + "\n";
//	   }
	   return _ret;
   	}

   /**
    * f0 -> "MOVE"
    * f1 -> Temp()
    * f2 -> Exp()
    */
   public R visit(MoveStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      Integer temp = (Integer) n.f1.accept(this, argu);
      if(n.f2.f0.which == 3) {
    	  String t = (String) n.f2.accept(this, argu);
    	  if(spilledArg.containsKey(temp)) {
    		  printValue += " MOVE v1 " + t + "\n";
    		  printValue += " ASTORE SPILLED ARG " + spilledArg.get(temp) + " v1 " + "\n";
    	  }
    	  else {
    		  String reg1 = getOneTempForUse(temp, true);
    		  printValue += " MOVE " + reg1 + " " + t + "\n"; 
    	  }
      }
      else
    	  n.f2.accept(this, (A) temp);
      
      return _ret;
   }

   /**
    * f0 -> "PRINT"
    * f1 -> SimpleExp()
    */
   public R visit(PrintStmt n, A argu) {
      R _ret=null;
      String reg = (String) n.f0.accept(this, argu);
      printValue += " PRINT " + reg + "\n";
      return _ret;
   }

   /**
    * f0 -> Call()
    *       | HAllocate()
    *       | BinOp()
    *       | SimpleExp()
    */
   public R visit(Exp n, A argu) {
      R _ret=null;
      return n.f0.accept(this, argu);
   }

   /**
    * f0 -> "BEGIN"
    * f1 -> StmtList()
    * f2 -> "RETURN"
    * f3 -> SimpleExp()
    * f4 -> "END"
    */
   public R visit(StmtExp n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      stmtCount++;
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      stmtCount++;
      String reg = (String) n.f3.accept(this, argu);
      printValue += " MOVE v0 " + reg + "\n";
      n.f4.accept(this, argu);
      stmtCount++;
      return _ret;
   }

   /**
    * f0 -> "CALL"
    * f1 -> SimpleExp()
    * f2 -> "("
    * f3 -> ( Temp() )*
    * f4 -> ")"
    */
   public R visit(Call n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      int temp = (Integer) argu;
      n.f2.accept(this, argu);
      //n.f3.accept(this, argu);
      Vector<Node> a = n.f3.nodes;
      int size = a.size();
      int i = 0;
      while(i < size && i<4) {
    	  int temp2 = (Integer) a.elementAt(i).accept(this, argu);
    	  String reg = getOneTempForUse(temp2, true);
    	  printValue += " MOVE a" + i + " " + reg + "\n";
    	  i++;
      }
      int k = 1;
      while( i < size) {
    	  int temp2 = (Integer) a.elementAt(i).accept(this, argu);
    	  String reg = getOneTempForUse(temp2, true);
    	  printValue += " PASSARG " + k + reg + "\n";
    	  i++;
    	  k++;
      }
      String reg = (String) n.f1.accept(this, argu);
      printValue += " CALL " + reg + "\n";
      n.f4.accept(this, argu);
      if(spilledArg.containsKey(temp)) {
    	  printValue += " ASTORE SPILLED ARG " + spilledArg.get(temp) + " v0 " + "\n";
      }
      else {
    	  String reg1 = getOneTempForUse(temp, true);
    	  printValue += " MOVE " + reg1 + " " + "v0" + "\n"; 
      }
      return _ret;
   }

   /**
    * f0 -> "HALLOCATE"
    * f1 -> SimpleExp()
    */
   public R visit(HAllocate n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String reg = (String) n.f1.accept(this, argu);
      int temp = (Integer) argu;
      if(spilledArg.containsKey(temp)) {
    	  printValue += " ASTORE SPILLED ARG " + spilledArg.get(temp) + " " + reg + "\n";
      }
      else {
    	  String reg1 = getOneTempForUse(temp, true);
    	  printValue += " MOVE " + reg1 + " HALLOCATE " + reg + "\n"; 
      }
      return (R) reg;
   }

   /**
    * f0 -> Operator()
    * f1 -> Temp()
    * f2 -> SimpleExp()
    */
   public R visit(BinOp n, A argu) {
      R _ret=null;
      String op = (String) n.f0.accept(this, argu);
      String reg1 = (String) n.f2.accept(this, argu);
      int temp2 = (Integer) n.f1.accept(this, argu);
      String reg2;
      if(reg1 == "v1") {
          reg2 = getOneTempForUse(temp2, false);
      }
      else {
    	  reg2 = getOneTempForUse(temp2, true);
      }
      int temp = (Integer) argu;
      if(spilledArg.containsKey(temp)) {
    	  printValue += " MOVE v1 " + op + " " + reg1 + " " + reg2 + "\n";
    	  printValue += " ASTORE SPILLED ARG " + spilledArg.get(temp) + " v1 " + "\n";
      }
      else {
    	  String reg = getOneTempForUse(temp, true);
    	  printValue += " MOVE " + reg + " " + op + " " + reg1 + " " + reg2 + "\n"; 
      }
      return _ret;
   }

   /**
    * f0 -> "LT"
    *       | "PLUS"
    *       | "MINUS"
    *       | "TIMES"
    */
   public R visit(Operator n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      if(n.f0.which == 0) return (R) "LT";
      if(n.f0.which == 1) return (R) "PLUS";
   	  if(n.f0.which == 2) return (R) "MINUS";
      return (R) "TIMES";
   }

   /**
    * f0 -> Temp()
    *       | IntegerLiteral()
    *       | Label()
    */
   public R visit(SimpleExp n, A argu) {
      R _ret=null;
      //n.f0.accept(this, argu);
      if(n.f0.which == 2) return n.f0.accept(this, argu);
      if(n.f0.which == 1) return (R) ((Integer) (n.f0.accept(this, argu))).toString();
      String reg = getOneTempForUse((Integer) n.f0.accept(this, argu), true);
      
      return (R) reg;
   }

   /**
    * f0 -> "TEMP"
    * f1 -> IntegerLiteral()
    */
   public R visit(Temp n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return n.f1.accept(this, argu);
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(IntegerLiteral n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return (R) Int(n.f0.toString());
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Label n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return (R) n.f0.toString();
   }

}
