//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */



public class GJNoArguDepthFirst<R> implements GJNoArguVisitor<R> {
   //
   // Auto class visitors--probably don't need to be overridden.
    //Hashtable<String, String> variableSymbolTable = new Hashtable<String, String>();
    void cryError(String message) {
        System.out.print("Type error");
        System.exit(1);
    }


    Hashtable<String, SymbolTable> global = new Hashtable<String, SymbolTable>();

    class Argument extends Object {
          String name;
          String type;
          Argument(String name, String type){
              this.name = name;
              this.type = type;
          }
          public void pretty(){
              System.out.println(name + " : " + type);
          }
        }

    class Signature extends Object{
        Vector<Argument> arguments;
        SymbolTable symbolTable;
        String returnType;
        public void appendArguments(){
            Enumeration vEnum = arguments.elements();
            while(vEnum.hasMoreElements()){
                Argument argument = (Argument) vEnum.nextElement();
                if(symbolTable.contains(argument.name))
                    cryError("append Error");
                else
                  symbolTable.variableSymbolTable.put(argument.name, argument.type);
            }
        }
        public void pretty(){
            int i = 0;
            System.out.println("Method arguments :");
            Enumeration vEnum = arguments.elements();
            while(vEnum.hasMoreElements()){
                Argument argument = (Argument) vEnum.nextElement();
                System.out.println(argument.type + " " + argument.name);
            }
            System.out.println("Return Type :");
            System.out.println(returnType);
            System.out.println("");
            //symbolTable.pretty();
        }
    }

    boolean contains(Vector<Argument> arguments, String name){
        Enumeration vEnum = arguments.elements();
        while(vEnum.hasMoreElements()){
            Argument argument = (Argument) vEnum.nextElement();
            if(argument.name.equals(name)){
                return true;
            }
        }
        return false;
    }

    class SymbolTable extends Object{
        Hashtable<String, String> variableSymbolTable;
        Hashtable<String, Signature> methodSymbolTable;
        String parent;
        SymbolTable(){
            parent = "main";
        }
        public R getVariable(String key){
            if(variableSymbolTable.containsKey(key))
                return (R) variableSymbolTable.get(key);
            else if(!parent.equals("main"))
                return global.get(parent).getVariable(key);
            return null;
        }

        public R getSignature(String key){
            if(methodSymbolTable.containsKey(key))
                return (R) methodSymbolTable.get(key);
            else if(!parent.equals("main"))
                return global.get(parent).getSignature(key);
            return null;
        }
        public boolean contains(String key){
            return variableSymbolTable.containsKey(key);
        }
        public void pretty(){
            Set entrySet = variableSymbolTable.entrySet();
            Iterator it = entrySet.iterator();
            System.out.println("variableSymbolTable :");
            while(it.hasNext()){
                System.out.println(it.next());
            }
            System.out.println("methodSymbolTable :");
            Enumeration e = methodSymbolTable.keys();
            while(e.hasMoreElements()){
                String key = (String) e.nextElement();
                System.out.println(key);
                System.out.println("");
                methodSymbolTable.get(key).pretty();
            }

            System.out.println("parent :");
            if(parent != null)
                System.out.println(parent);
            else
                System.out.println("none");
            System.out.println("");
        }
    }



    SymbolTable currentSymbolTable;
    String currentClass;
    Hashtable<String, String> currentHashIdentifiers;
    Hashtable<String, Signature> currentHashMethods;
    Vector<Argument> currentArguments;
    //
   public R visit(NodeList n) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeListOptional n) {
      if ( n.present() ) {
         R _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n) {
      if ( n.present() )
         return n.node.accept(this);
      else
         return null;
   }

   public R visit(NodeSequence n) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeToken n) { return null; }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> MainClass()
    * f1 -> ( TypeDeclaration() )*
    * f2 -> <EOF>
    */
   public R visit(Goal n) {
      R _ret=null;
      String k = "int[]";
      global.put(k, new SymbolTable());
      k = "int";
      global.put(k, new SymbolTable());
      k = "boolean";
      global.put(k, new SymbolTable());
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      return (R) global;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> "public"
    * f4 -> "static"
    * f5 -> "void"
    * f6 -> "main"
    * f7 -> "("
    * f8 -> "String"
    * f9 -> "["
    * f10 -> "]"
    * f11 -> Identifier()
    * f12 -> ")"
    * f13 -> "{"
    * f14 -> PrintStatement()
    * f15 -> "}"
    * f16 -> "}"
    */
   public R visit(MainClass n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
      n.f8.accept(this);
      n.f9.accept(this);
      n.f10.accept(this);
      n.f11.accept(this);
      n.f12.accept(this);
      n.f13.accept(this);
      n.f14.accept(this);
      n.f15.accept(this);
      n.f16.accept(this);
      return _ret;
   }

   /**
    * f0 -> ClassDeclaration()
    *       | ClassExtendsDeclaration()
    */
   public R visit(TypeDeclaration n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> ( VarDeclaration() )*
    * f4 -> ( MethodDeclaration() )*
    * f5 -> "}"
    */
   public R visit(ClassDeclaration n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      currentClass = n.f1.f0.toString();
      if(global.containsKey(currentClass)) {
          cryError("Redeclaration of class");
      }
      currentSymbolTable = new SymbolTable();
      currentHashIdentifiers = new Hashtable<String, String>();
      currentHashMethods = new Hashtable<String, Signature>();
      currentHashIdentifiers = new Hashtable<String, String>();
      currentHashMethods = new Hashtable<String, Signature>();
      currentSymbolTable.variableSymbolTable = currentHashIdentifiers;
      currentSymbolTable.methodSymbolTable = currentHashMethods;
      currentSymbolTable.parent = (String) "main";
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      global.put(currentClass, currentSymbolTable);
      n.f5.accept(this);
      //System.out.println(currentClass);
      //currentSymbolTable.pretty();
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "extends"
    * f3 -> Identifier()
    * f4 -> "{"
    * f5 -> ( VarDeclaration() )*
    * f6 -> ( MethodDeclaration() )*
    * f7 -> "}"
    */
   public R visit(ClassExtendsDeclaration n) {
      R _ret=null;
      n.f0.accept(this);
      currentClass = (String) n.f1.accept(this);
      if(global.containsKey(currentClass)) {
          cryError("Redeclaration of class");
      }
      n.f2.accept(this);
      SymbolTable currentSymbolTable = new SymbolTable();
      String parent = (String) n.f3.accept(this);
      //if(!global.containsKey(parent))
      //    cryError("No Parent Found");
      currentHashIdentifiers = new Hashtable<String, String>();
      currentHashMethods = new Hashtable<String, Signature>();
      currentSymbolTable.variableSymbolTable = currentHashIdentifiers;
      currentSymbolTable.methodSymbolTable = currentHashMethods;
      currentSymbolTable.parent = parent;
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
      global.put(currentClass, currentSymbolTable);
      //System.out.println(currentClass);
      //currentSymbolTable.pretty();
      return _ret;
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    * f2 -> ";"
    */
   public R visit(VarDeclaration n) {
      R _ret=null;
      String type = (String) n.f0.accept(this);
      String name = (String) n.f1.accept(this);
      n.f2.accept(this);
      if(!currentHashIdentifiers.containsKey(name))
          currentHashIdentifiers.put(name, type);
      else
          cryError("Redeclaration of Variable");
      return _ret;
   }

   /**
    * f0 -> "public"
    * f1 -> Type()
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( FormalParameterList() )?
    * f5 -> ")"
    * f6 -> "{"
    * f7 -> ( VarDeclaration() )*
    * f8 -> ( Statement() )*
    * f9 -> "return"
    * f10 -> Expression()
    * f11 -> ";"
    * f12 -> "}"
    */
   public R visit(MethodDeclaration n) {
      R _ret=null;
      n.f0.accept(this);
      SymbolTable currentMethodTable = new SymbolTable();
      String returnType = (String) n.f1.accept(this);
      String methodName = (String) n.f2.accept(this);
      if(currentHashMethods.containsKey(methodName))
          cryError("overloading");
      n.f3.accept(this);
      currentArguments = new Vector<Argument>();
      n.f4.accept(this);
      Signature methodSign = new Signature();
      methodSign.arguments = currentArguments;
      methodSign.returnType = returnType;
      currentHashIdentifiers = new Hashtable<String, String>();
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
      n.f8.accept(this);
      n.f9.accept(this);
      n.f10.accept(this);
      n.f11.accept(this);
      n.f12.accept(this);

      currentMethodTable.variableSymbolTable = currentHashIdentifiers;
      currentMethodTable.methodSymbolTable = new Hashtable<String, Signature>();
      currentMethodTable.parent = currentClass;
      methodSign.symbolTable = currentMethodTable;
      methodSign.appendArguments();
      currentHashMethods.put(methodName, methodSign);
      return _ret;
   }

   /**
    * f0 -> FormalParameter()
    * f1 -> ( FormalParameterRest() )*
    */
   public R visit(FormalParameterList n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    */
   public R visit(FormalParameter n) {
      R _ret=null;
      String type = (String) n.f0.accept(this);
      String name = (String) n.f1.accept(this);
      if(!contains(currentArguments, name))
          currentArguments.add(new Argument(name, type));
      else
          cryError("repetition in arguments");
      return _ret;
   }

   /**
    * f0 -> ","
    * f1 -> FormalParameter()
    */
   public R visit(FormalParameterRest n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> ArrayType()
    *       | BooleanType()
    *       | IntegerType()
    *       | Identifier()
    */
   public R visit(Type n) {
      R _ret=null;
      String type = (String) n.f0.accept(this);
      return (R) type;
   }

   /**
    * f0 -> "int"
    * f1 -> "["
    * f2 -> "]"
    */
   public R visit(ArrayType n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      String type = "int[]";
      return (R) type;
   }

   /**
    * f0 -> "boolean"
    */
   public R visit(BooleanType n) {
      R _ret=null;
      n.f0.accept(this);
      String type = "boolean";
      return (R) type;
   }

   /**
    * f0 -> "int"
    */
   public R visit(IntegerType n) {
      R _ret=null;
      n.f0.accept(this);
      String type = "int";
      return (R) type;
   }

   /**
    * f0 -> Block()
    *       | AssignmentStatement()
    *       | ArrayAssignmentStatement()
    *       | IfStatement()
    *       | WhileStatement()
    *       | PrintStatement()
    */
   public R visit(Statement n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> "{"
    * f1 -> ( Statement() )*
    * f2 -> "}"
    */
   public R visit(Block n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> "="
    * f2 -> Expression()
    * f3 -> ";"
    */
   public R visit(AssignmentStatement n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> "["
    * f2 -> Expression()
    * f3 -> "]"
    * f4 -> "="
    * f5 -> Expression()
    * f6 -> ";"
    */
   public R visit(ArrayAssignmentStatement n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      return _ret;
   }

   /**
    * f0 -> "if"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    * f5 -> "else"
    * f6 -> Statement()
    */
   public R visit(IfStatement n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      return _ret;
   }

   /**
    * f0 -> "while"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public R visit(WhileStatement n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      return _ret;
   }

   /**
    * f0 -> "System.out.println"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> ";"
    */
   public R visit(PrintStatement n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      return _ret;
   }

   /**
    * f0 -> AndExpression()
    *       | CompareExpression()
    *       | PlusExpression()
    *       | MinusExpression()
    *       | TimesExpression()
    *       | ArrayLookup()
    *       | ArrayLength()
    *       | MessageSend()
    *       | PrimaryExpression()
    */
   public R visit(Expression n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "&"
    * f2 -> PrimaryExpression()
    */
   public R visit(AndExpression n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "<"
    * f2 -> PrimaryExpression()
    */
   public R visit(CompareExpression n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      return _ret;
    }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "+"
    * f2 -> PrimaryExpression()
    */
   public R visit(PlusExpression n) {
       R _ret=null;
       n.f0.accept(this);
       n.f1.accept(this);
       n.f2.accept(this);
       return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "-"
    * f2 -> PrimaryExpression()
    */
   public R visit(MinusExpression n) {
       R _ret=null;
       n.f0.accept(this);
       n.f1.accept(this);
       n.f2.accept(this);
       return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "*"
    * f2 -> PrimaryExpression()
    */
   public R visit(TimesExpression n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      return _ret;
   }
   /**
    * f0 -> PrimaryExpression()
    * f1 -> "["
    * f2 -> PrimaryExpression()
    * f3 -> "]"
    */
   public R visit(ArrayLookup n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> "length"
    */
   public R visit(ArrayLength n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( ExpressionList() )?
    * f5 -> ")"
    */
   public R visit(MessageSend n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      return _ret;
   }

   /**
    * f0 -> Expression()
    * f1 -> ( ExpressionRest() )*
    */
   public R visit(ExpressionList n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> ","
    * f1 -> Expression()
    */
   public R visit(ExpressionRest n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> IntegerLiteral()
    *       | TrueLiteral()
    *       | FalseLiteral()
    *       | Identifier()
    *       | ThisExpression()
    *       | ArrayAllocationExpression()
    *       | AllocationExpression()
    *       | NotExpression()
    *       | BracketExpression()
    */
   public R visit(PrimaryExpression n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(IntegerLiteral n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> "true"
    */
   public R visit(TrueLiteral n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> "false"
    */
   public R visit(FalseLiteral n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Identifier n) {
      R _ret=null;
      n.f0.accept(this);
      return (R) n.f0.toString();

   }

   /**
    * f0 -> "this"
    */
   public R visit(ThisExpression n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> "new"
    * f1 -> "int"
    * f2 -> "["
    * f3 -> Expression()
    * f4 -> "]"
    */
   public R visit(ArrayAllocationExpression n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f4.accept(this);
      return _ret;
   }

   /**
    * f0 -> "new"
    * f1 -> Identifier()
    * f2 -> "("
    * f3 -> ")"
    */
   public R visit(AllocationExpression n) {
      R _ret=null;
      n.f0.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      return _ret;
   }

   /**
    * f0 -> "!"
    * f1 -> Expression()
    */
   public R visit(NotExpression n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> "("
    * f1 -> Expression()
    * f2 -> ")"
    */
   public R visit(BracketExpression n) {
      R _ret=null;
      n.f0.accept(this);
      n.f2.accept(this);
      return _ret;
   }

}

